---

- name: getting current Time
  setup:
    gather_subset:
      - date_time
  register: playEndTime


- name: Toggle play status depending on exception
  set_fact:
    is_all_task_success: " No "
  when: hostvars['DUMMY_HOST'] is defined



- name: Update log file
  lineinfile:
    #path: "winReport_{{ tower_job_id }}_{{ ansible_date_time.date }}.csv"
    path: "{{ report_file_name }}"
    line: "{{ req_no_creation_date }},{{ playStartDate }},{{playStartTime}},{{playEndTime.ansible_facts.ansible_date_time.time}},{{req_account_name}},{{ansible_play_name}},{{req_no}},{{req_short_description}},{{cartridge_form_id}},{{ task_name }}, {{ is_all_task_success }}, {{ ansible_hostname }}, {{ exceptionMsg }}"
    create: yes
    #run_once: True
  delegate_to: localhost

