---
# tasks file for mso_joiner
- import_role:
         name: bulk_common_utilities
         tasks_from: pre_reqs
- import_role:
         name: bulk_common_utilities
         tasks_from: get_resource_details

- include_tasks: mso_check_user_ad.yml
- include_tasks: mso_joiner_ad.yml
#- include_tasks: mso_joiner_storage.yml
