---
# tasks file for mso_leaver
- import_role:
         name: bulk_common_utilities
         tasks_from: pre_reqs
- import_role:
         name: bulk_common_utilities
         tasks_from: get_resource_details
         
- include_tasks: mso_leaver_ad.yml
#- include_tasks: mso_leaver_storage.yml
